
#ifndef CONFIG_H
#define CONFIG_H

// Choose amongst TEXTDEMO, LRSDEMO, HRSDEMO, COLORDEMO
#define COLORDEMO

/*
 *  SCREEN DIMENSION
 */

#ifdef TEXTDEMO
#define SCREEN_WIDTH 40
#define SCREEN_HEIGHT 26
#endif

#ifdef LRSDEMO
#define ANGLEONLY
#define USE_ZBUFFER
#define USE_COLLISION_DETECTION
#define SCREEN_WIDTH 40
#define SCREEN_HEIGHT 26
#endif

#ifdef COLORDEMO
#define ANGLEONLY
#define USE_ZBUFFER
#define USE_COLOR
#define USE_COLLISION_DETECTION
#define SCREEN_WIDTH 40
#define SCREEN_HEIGHT 26
#endif


#ifdef HRSDEMO
#define USE_HIRES_RASTER
#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 200
#endif

/*
 *  BUFFERS DIMENSION
 */

#define NB_MAX_POINTS 64
#define NB_MAX_SEGMENTS 64
#define NB_MAX_FACES 64
#define NB_MAX_PARTICULES 64
/*
 *  SCREEN MEMORY
 */
#define ADR_BASE_SCREEN 48040  //BB80

/*
 *  ELEMENTS SIZE
 */

#define SIZEOF_3DPOINT 4
#define SIZEOF_SEGMENT 4
#define SIZEOF_PARTICULE 2
#define SIZEOF_2DPOINT 4
#define SIZEOF_FACES 4



#ifdef TARGET_ORIX
#undef USE_ASM_HFILL
#define USE_C_HFILL
#define USE_C_INITFRAMEBUFFER
#undef USE_ASM_INITFRAMEBUFFER
#define USE_C_ZPLOT
#undef  USE_ASM_ZPLOT
#define USE_C_ZLINE
#undef USE_ASM_ZLINE
#define USE_C_BRESFILL
#undef USE_ASM_BRESFILL
#define USE_C_ZBUFFER
#undef USE_ASM_ZBUFFER
#undef USE_ASM_BUFFER2SCREEN
#else
#undef USE_C_HFILL
#define USE_ASM_HFILL
#define USE_C_INITFRAMEBUFFER
#undef USE_ASM_INITFRAMEBUFFER
#define USE_C_ZPLOT
#undef  USE_ASM_ZPLOT
#undef USE_C_ZLINE
#define USE_ASM_ZLINE
#define USE_C_BRESFILL
#undef USE_ASM_BRESFILL
#undef USE_C_ZBUFFER
#define USE_ASM_ZBUFFER
#undef USE_ASM_BUFFER2SCREEN
#define USE_C_BUFFER2SCREEN
#endif


#undef USE_MULTI40

#endif
