@ECHO OFF

::
:: Set the build paremeters
::
SET OSDKADDR=$500
SET OSDKNAME=GLORIC
SET OSDKCOMP=-O2
REM SET OSDKLINK=-B

SET OSDKFILE=start glOric_c glOric_s

REM SET OSDKFILE=main
REM 
REM SET OSDKFILE=%OSDKFILE%  profile
REM SET OSDKFILE=%OSDKFILE%  glOric kernel
REM SET OSDKFILE=%OSDKFILE% lrsDemo
REM SET OSDKFILE=%OSDKFILE% hrsDemo
REM SET OSDKFILE=%OSDKFILE% txtDemo
REM SET OSDKFILE=%OSDKFILE% rtDemo
REM SET OSDKFILE=%OSDKFILE% colorDemo
REM SET OSDKFILE=%OSDKFILE% profbench
REM SET OSDKFILE=%OSDKFILE% colors
REM SET OSDKFILE=%OSDKFILE% glProject8
REM SET OSDKFILE=%OSDKFILE% glProject
REM SET OSDKFILE=%OSDKFILE% zbuffer
REM SET OSDKFILE=%OSDKFILE% render\zbuff
REM 
REM SET OSDKFILE=%OSDKFILE% lrsDrawing
REM SET OSDKFILE=%OSDKFILE% hrsDrawing
REM SET OSDKFILE=%OSDKFILE% geom
REM SET OSDKFILE=%OSDKFILE% logic
REM SET OSDKFILE=%OSDKFILE% keyboard
REM SET OSDKFILE=%OSDKFILE% bresfill
REM SET OSDKFILE=%OSDKFILE% math\atan2 math\norm
REM 
REM 
REM SET OSDKFILE=%OSDKFILE% render\lrsSegments
REM SET OSDKFILE=%OSDKFILE% render\face
REM 
REM SET OSDKFILE=%OSDKFILE% raster\buffer raster\line8
REM SET OSDKFILE=%OSDKFILE% raster\fill8 raster\line
REM SET OSDKFILE=%OSDKFILE% raster\seg8
REM SET OSDKFILE=%OSDKFILE% raster\raster8
REM SET OSDKFILE=%OSDKFILE% raster\particules
REM SET OSDKFILE=%OSDKFILE% raster\filler
REM SET OSDKFILE=%OSDKFILE% raster\hzfill
REM 
REM SET OSDKFILE=%OSDKFILE% util\print util\screen util\display util\rand

:: List of files to put in the DSK file.
:: Implicitely includes BUILD/%OSDKNAME%.TAP
SET OSDKTAPNAME="glOric"

::run99.tap ..\intro\build\intro.tap
SET OSDKDNAME=" -- glOric --"
SET OSDKINIST="?\"V1.1\":WAIT20:!RUNME.COM"
